package:
  name: rescript
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - ncbi-datasets-pyclient >=17.0.0
  - requests
  - xmltodict
  - py7zr
  - pandas {{ pandas }}
  - vsearch >=2.21.1
  - scikit-learn {{ scikit_learn }}
  - scikit-bio {{ scikit_bio }}
  - q2-types >={{ q2_types }}
  - q2-feature-classifier >={{ q2_feature_classifier }}
  - q2-vizard >={{ q2_vizard }}
  - q2-alignment >={{ q2_alignment }}
  - qiime2 >={{ qiime2 }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - pytest
  - q2-types >={{ q2_types }}
  - q2-feature-classifier >={{ q2_feature_classifier }}
  - q2-vizard >={{ q2_vizard }}
  - q2-alignment >={{ q2_alignment }}
  - qiime2 >={{ qiime2 }}
  imports:
  - rescript
  - qiime2.plugins.rescript
  commands:
  - py.test --pyargs rescript
about:
  home: https://github.com/bokulich-lab/RESCRIPt
  license: BSD-3-Clause
  license_family: BSD
