{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: rescript
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - ncbi-datasets-pylib >=14.13.0
    - requests
    - xmltodict
    - pandas {{ pandas }}
    - vsearch >=2.21.1
    - scikit-learn {{ scikit_learn }}
    - scikit-bio {{ scikit_bio }}
    - q2-types {{ qiime2_epoch }}.*
    - q2-feature-classifier {{ qiime2_epoch }}.*
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - pytest
    - q2-types >={{ q2_types }}
    - q2-feature-classifier >={{ q2_feature_classifier }}
    - qiime2 >={{ qiime2 }}

  imports:
    - rescript
    - qiime2.plugins.rescript

  commands:
    - py.test --pyargs rescript

about:
  home: https://github.com/bokulich-lab/RESCRIPt
  license: BSD-3-Clause
  license_family: BSD
