# Example of workflow trigger for calling workflow (the client).
name: ci-dev
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
jobs:
  ci:
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: amplicon
